# Generated by Django 4.2.4 on 2023-08-27 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_user', models.BigIntegerField()),
                ('team', models.CharField(db_index=True, max_length=16)),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16)),
                ('pwd', models.CharField(max_length=16)),
                ('team', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('subtask_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team', models.CharField(db_index=True, max_length=16)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, to='danbi_app.task')),
            ],
        ),
    ]
