# Generated by Django 4.2.4 on 2023-08-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danbi_app', '0002_task_danbi_app_t_team_efd057_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['team'], name='danbi_app_s_team_8ae4d9_idx'),
        ),
    ]
