# Generated by Django 4.2.4 on 2023-08-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danbi_app', '0004_alter_subtask_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
